What is Numpy?
Ans It is a python package for numeric computing.It provides powerful ways to create store and manipulate data, which makes it able to seamlessly and speedily integrate with a wide variety of databases and data formats. This is also the foundation that Pandas is built on which is a high performance data-centric package that we're going to learn more about in this course. In this lecture, we're going to talk about creating arrays with certain data types, manipulating arrays ,selecting elements from arrays and loading data sets into arrays.

In [2]:
#Importing Numpy
import numpy as np

In [4]:
#Creating Array -> Pass List As an argument
#Array -> It is a list or list of lists.

In [5]:
#1D ARRAY -> List
arr1 = np.array([1,2,3,4])
print(arr1)
print(arr1.ndim) #ndim attribute print dimension of array.

[1 2 3 4]
1


In [6]:
#Multi-Dimensional ARRAY -> List Of lists -> Matrix
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)
print(arr2.ndim)

[[1 2 3]
 [4 5 6]]
2


Other Numpy Function -> shape and dtype

In [7]:
#Shape -> Check dimensions of array and gives a tuple
print(arr2.shape)
print(type(arr2.shape))

(2, 3)
<class 'tuple'>


In [8]:
#dtype -> Gives Type Of Items Stored In Array
print(arr2.dtype)

int32


Important Note -> Numpy will try and give you the best data type format possible to keep your data types homogeneous, which means that they're all the same in the array. 

Sometimes we know the shape of an array that we want to create, but not what we want to be in it. None by offer several functions, to create arrays with initial placeholders 

In [9]:
#Placeholder - 0
arr3 = np.zeros((2,3))
print(arr3)

[[0. 0. 0.]
 [0. 0. 0.]]


In [10]:
#Placeholder - 1
arr4 = np.ones((3,2))
print(arr4)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [11]:
#Placeholder - Random Values
arr5 = np.random.rand(5,4)
print(arr5)

[[0.66957561 0.99790572 0.27594304 0.34282589]
 [0.53000292 0.79332547 0.5812059  0.28434379]
 [0.17223717 0.84403019 0.90948249 0.04095247]
 [0.43558485 0.38667206 0.38492673 0.14387289]
 [0.16758718 0.19257889 0.76805715 0.88188009]]


Create Arrays as a list of numbers / sequence using arrange function

In [12]:
#Array with multiples of 5 -> arrange(L.B(Inclusive),U.B(Exclusive),Diff)

In [13]:
arr6 = np.arange(5,50,5)
print(arr6)
print(arr6.shape)

[ 5 10 15 20 25 30 35 40 45]
(9,)


Linspace -> Generate a seuence of floats diff from arange is that its 3rd argument is no. of items you want to generate

In [14]:
arr7 = np.linspace(1,2,25) # Generate 25 floating point numbers
print(arr7)

[1.         1.04166667 1.08333333 1.125      1.16666667 1.20833333
 1.25       1.29166667 1.33333333 1.375      1.41666667 1.45833333
 1.5        1.54166667 1.58333333 1.625      1.66666667 1.70833333
 1.75       1.79166667 1.83333333 1.875      1.91666667 1.95833333
 2.        ]


 # ARRAY OPERATIONS

Operations On Array -> 
i) Mathematical Manipulation -> Addition,Subtraction,Exponent,Square,Boolean Array(Binary Values)
ii) Matrix Manipulation -> product,transpose,inverse

Arithmetic Operations -> +,-,*,/ -> Elt. Otherwise

In [3]:
#Addition
t1 = np.array([1,2,3,4])
t2 = np.array([5,6,7,8])
t3 = t1 + t2
print(t3)

[ 6  8 10 12]


In [5]:
#Subtraction,Multiplication and Divison
t4 = t1-t2
t5 = t1*t2
t6 = t1/t2
print(t4)
print(t5)
print(t6)

[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]


In [7]:
t10 = np.array([[1],[2],[3]])
print(t10*t2)

[[ 5  6  7  8]
 [10 12 14 16]
 [15 18 21 24]]


#Arithmetic manipulation, we can convert current data to the way we want it to be. So here's a real world problem that I faced. I moved down to the United States about six years ago from Canada. In Canada, we use Celsius for temperatures and my wife still hasn't converted to the US system, which uses Fahrenheit. With numpy I could easily convert a number of Fahrenheit values, say, the weather forecast to Celsius for her. So, let's create an array of typical Ann Arbor winter Fahrenheit values. So, fahrenheit equals np.array and sometimes it'll be zero degrees Fahrenheit, may be minus 10 minus 5 minus 15 or 0.

In [9]:
farenheit = np.array([0,-10,-15,-5,0])
celsius = ((farenheit-32)*5)/9
print(celsius)

[-17.77777778 -23.33333333 -26.11111111 -20.55555556 -17.77777778]


In [ ]:
#Boolean Array -> Return True If Condition is True And False If Condition is false (w.r.t elt)

In [10]:
celsius > -20

array([ True, False, False, False,  True])

Check Odd or Even In An Array

In [15]:
nums = np.array([1,2,3,467,32])
nums % 2 == 0

array([False,  True, False, False,  True])

In [ ]:
#Matrix Manipulation -> Do Operations With Matrix
#Matrix Product

In [15]:
#We use @ sign for matrix product
m1 = np.array([1,2,3])# 1 X 3 Matrix
m2 = np.array([[1],[2],[3]]) # 3 X 1 Matrix
print(m1@m2)

[14]


Recall that matrix multiplication is only possible when ineer dimensions of the matrix is same. 
Ex -> 2 X 3 and 3 X 4 -> 2 X 4(Possible)
Ex -> 2 X 1 and 3 X 2 -> Not Possible

AGGREGATE FUNCTIONS ON MATRIX -> max(),min(),sum(),mean()

In [17]:
test_array = np.array([[1,2,3],[4,5,6]])
print("Sum ->",test_array.sum())
print("Mean ->",test_array.mean())
print("Max ->",test_array.max())
print("Min ->",test_array.min())

Sum -> 21
Mean -> 3.5
Max -> 6
Min -> 1


In [19]:
#Create array with 15 elt ranging 1 to 15 in dimension of 3 X 5
my_arr=np.arange(1,16,1).reshape(3,5)#To change dimension to 3 X 5
print(my_arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


Numpy comes into play in something like images. For this demonstration, I'm going to use the Python Imaging Library, PIL and a function to display images in the Jupyter notebook

In [21]:
from PIL import Image #PIL -> Python Image Library
from IPython.display import display #Func to display images

In [25]:
#Image Manipulation can also be done through numpy arrays. (Not discussed) I'm quite busy with other things.

#Indexing, Slicing And Iterating

<h1>>Importance -> Indexing, slicing and iterating are extremely important for data manipulation and analysis. Because these techniques allow us to select data based on conditions and copy or update the data. </h1>

In [3]:
#Indexing
#In 1-D Arrays it works in same manner as lists.
ind_array = np.array([1,2,3,5,6])
for i in range(0,5):
    print("Element At Index",i,"is",ind_array[i])


Element At Index 0 is 1
Element At Index 1 is 2
Element At Index 2 is 3
Element At Index 3 is 5
Element At Index 4 is 6


In [ ]:
#In 2-D Arrays num[1,1] RowNo,ColNo

In [5]:
two_array = np.array([[1,2],[3,4],[5,6]])
print(two_array[0,1])

2


#Boolean Indexing -> Boolean indexing allows us to select arbitrary elements based on conditions. 

In [6]:
sha_arr = np.array([[1,2],[3,4],[5,6]])
mas_arr = sha_arr%2==0
print(mas_arr)

[[False  True]
 [False  True]
 [False  True]]


In [9]:
print(sha_arr[mas_arr])#Will Return True Values Correspnding to original arr and mass arr in form of 1D Array.

[2 4 6]


#Slicing -> In 1-D arr, it works same as lists (Use the : )

In [11]:
sli_arr = np.array([1,2,3,4])
print(sli_arr[:3])# 0 1 2 index 

[1 2 3]


#Slicing In Case Of Multi Dimensional Arrays

In [14]:
two_d_arr = np.arange(1,16,1).reshape(3,5)
print(two_d_arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [ ]:
# :3 row 0 and row 1 and row 2 will be printed

In [16]:
two_d_arr[:2] #Oth And 1th Row

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [17]:
# Second argument a:b column a to b(exclusive)
two_d_arr[1:2,2:3]

array([[8]])

In [ ]:
#If you modify a specific elt then original value will be chnaged (mutable)
#Q -> Change 13 to 17 in two_d_arr

In [18]:
#Ans 
two_d_arr[2:3,2:3]=17
print(two_d_arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 17 14 15]]


In [ ]:
Trying Numpy With Data Sets

In [ ]:
#We are going to take example of rohit.csv in which his stats has been given like avg,runs,100s,matches.50s

To load a dataset into numpy, we can use the genfrom text function. We can specify data file name, the delimiter which is optional but we often use it and the number of rows to skip if we have a header row.

the genfrom text function has a parameter called d-type for specifying data types for each column and this parameter is optional. Without specifying the type, all types will be casted to a more general or precise type. So there will be some inference done.

In [9]:
records_of_hitman = np.genfromtxt("rohit.csv", delimiter=",", skip_header=1)

In [8]:
records_of_hitman

array([[5.802e+01, 5.135e+01, 4.826e+01, 4.593e+01, 3.776e+01],
       [2.379e+03, 8.730e+02, 7.240e+02, 2.021e+03, 9.820e+02],
       [8.000e+00, 2.000e+00, 2.000e+00, 6.000e+00, 2.000e+00],
       [4.500e+01, 1.900e+01, 2.000e+01, 5.500e+01, 2.900e+01],
       [9.000e+00, 8.000e+00, 4.000e+00, 9.000e+00, 5.000e+00]])

In [10]:
#Converting Into Readable Values
np.set_printoptions(suppress=True)

In [11]:
records_of_hitman

array([[  58.02,   51.35,   48.26,   45.93,   37.76],
       [2379.  ,  873.  ,  724.  , 2021.  ,  982.  ],
       [   8.  ,    2.  ,    2.  ,    6.  ,    2.  ],
       [  45.  ,   19.  ,   20.  ,   55.  ,   29.  ],
       [   9.  ,    8.  ,    4.  ,    9.  ,    5.  ]])

In [12]:
#If we want to access 1st Column
#i) All rows combined but only first Column
print(records_of_hitman[:,0])

[  58.02 2379.      8.     45.      9.  ]


In [13]:
#ii) In Separate Rows
print(records_of_hitman[:,0:1])

[[  58.02]
 [2379.  ]
 [   8.  ]
 [  45.  ]
 [   9.  ]]


#What if we want several non-consecutive columns? Well, we can place the indices of the columns that we want into an array and past that array as the second argument. 

In [14]:
print(records_of_hitman[:,[0,1,3]])

[[  58.02   51.35   45.93]
 [2379.    873.   2021.  ]
 [   8.      2.      6.  ]
 [  45.     19.     55.  ]
 [   9.      8.      9.  ]]


In [ ]:
#Suppose , we want to calculate total average of Rohit Sharma (First Row)

In [15]:
print(records_of_hitman[0].mean())

48.263999999999996


In [16]:
report = np.genfromtxt('report.csv',dtype=None,delimiter=',',skip_header=1,names=('ID','Math Score','Science Score','English Score','Attendance'))

In [17]:
report

array([( 1, 78.5, 85. , 92.3, 95), ( 2, 82.3, 74.6, 89.1, 90),
       ( 3, 69.8, 80.2, 87.5, 85), ( 4, 88.1, 92.3, 79.9, 98),
       ( 5, 74.4, 65.2, 91.3, 93), ( 6, 90.2, 88.4, 85. , 97),
       ( 7, 67.5, 70.1, 76.2, 88), ( 8, 79.3, 84.6, 82.4, 92),
       ( 9, 85.7, 89.9, 91. , 96), (10, 71.6, 78.5, 80.9, 87)],
      dtype=[('ID', '<i4'), ('Math_Score', '<f8'), ('Science_Score', '<f8'), ('English_Score', '<f8'), ('Attendance', '<i4')])

In [19]:
report.shape #We are getting 10 tuples.

(10,)

In [22]:
#Let's Print Math Scores Of All Students With Their Id OF FIRST 5 STUDENTS
print('STUDNET ID ->',report['ID'][:5])

STUDNET ID -> [1 2 3 4 5]


In [ ]:
#If we want maths marks by percentage we will divide it by total marks(95) and multiplying by 100

In [24]:
report['Math_Score']=report['Math_Score']*(100/95)
report['Math_Score']

array([82.63157895, 86.63157895, 73.47368421, 92.73684211, 78.31578947,
       94.94736842, 71.05263158, 83.47368421, 90.21052632, 75.36842105])

<h1>END OF NUMPY</h1>